bool wifiOn();
void wifiOff();
void IRAM_ATTR rainTick(void);
void debug( const char* format, ... );
void IRAM_ATTR windTick(void);
void printLocalTime();
void printTimeNextWake();
void readSensorsData(struct sensorData *environment);
void readMoonPhase(struct sensorData *environment);
void readEto(struct sensorData *environment);
void readBattery (struct sensorData *environment);
void readUvIndex(struct sensorData *environment);
void readBME(struct sensorData *environment);
void readLux(struct sensorData *environment);
void readTemperature (struct sensorData *environment);
void readIrradiation(struct sensorData *environment);
void sendData(struct sensorData enviroment);
int moonPhases(unsigned long time);
char * moonPhaseToString(int phase);